= Python

:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

=== Important Bulletpoints:

* When trying to determine the code that they need to solve a particular problem, Python programmers often favor experimenting with code snippets at the shell.
The shell provides two interactive functions that work at the `>>>` prompt. The `dir` function lists an object’s attributes, whereas `help` provides access to the Python docs.

=== Meet the four Built-in Data Structures.

Python comes with four built-in data structures that you can use to hold any collection of objects, and they are *list, tuple, dictionary*, and *set*.
Note that by “built-in” we mean that lists, tuples, dictionaries, and sets are always available to your code and they do not need to be imported prior to use: each of these
data structures is part of the language.

* List: An ordered mutable collection of objects. A list in Python is very similar to the notion of an array in other programming languages

* Tuple: An ordered immutable collection of objects. A tuple is an immutable list. This means that once you assign objects to a tuple,
the tuple cannot be changed under any circumstance.

* Dictionary: An unordered set of key/value pairs Depending on your programming background, you may already know what a
dictionary is, but you may know it by another name, such as associative array, map, symbol table, or hash.

[WARNING]
Something to watch out for when using a dictionary is that you cannot rely upon the internal ordering used by the interpreter. Specifically, the order
in which you add key/value pairs to a dictionary is not maintained by the interpreter, and has no meaning (to Python).

* Set: An unordered set of unique objects. In Python, a set is a handy data structure for remembering a collection of
related objects while ensuring none of the objects are duplicated. The fact that sets let you perform unions, intersections, and differences is an
added bonus (especially if you are a math type who loves set theory). Sets, like lists and dictionaries, can grow (and shrink) as needed. Like dictionaries,
sets are unordered, so you cannot make assumptions about the order of the objects in your set.


Source: Head-First Python Book.

=== Clean Code Practices:

[IMPORTANT]
Stop writing Python functions that take more than three minutes to understand!

Have you ever looked at a function you wrote one month earlier and found it difficult to understand in 3 minutes? If that is the case, it is time to refactor your code. If it takes you more than 3 minutes to understand your code, imagine how long it would take for your teammates to understand your code.
If you want your code to be reusable, you want it to be readable. +
These practices will make your functions more readable and easier to detect errors.


* Small:
** A function should be small because it is easier to know what the function does. How small is small?
There should rarely be more than 20 lines of code in one function. It can be as small as below.
The indent level of a function should not be greater than one or two.

* Do One Task:
** A function should complete only one task, not multiple tasks.

* One Level Of Abstraction:
[quote, PCMag]
The level of abstraction is the amount of complexity by which a system is viewed or programmed.
The higher the level, the less detail. The lower the level, the more detail.
+
** To make the code within the function to be at the same level of abstraction, we can put the low-level code into another function.

* Duplication:
** We should avoid duplication because:
*** It is redundant
*** If we make a change to one piece of code, we need to remember to make the same change to another piece of code. If we forget to do so, we will introduce bugs into our code.

** We can eliminate duplication by putting the duplicated code into a function.

* Descriptive Names:
[quote, Clean Code by Robert C. Martin]
A long descriptive name is better than a short enigmatic name. A long descriptive name is better than a long descriptive comment.
+
** Don’t be afraid to write long names. It is better to write long names rather than write vague names.

* Have Fewer than 4 Arguments:
** A function should not have more than 3 arguments since it is a sign that the function is performing multiple tasks.
It is also difficult to test a function with more than 3 different combinations of variables.
+
[TIP]
If a function has more than 3 arguments, consider turning it into a class.

Source: https://towardsdatascience.com/python-clean-code-6-best-practices-to-make-your-python-functions-more-readable-7ea4c6171d60[towardsdatascience]
